### PR TITLE
fixing issue where renderjson was throwing an exception in the install…

### LINKED ISSUE #672: renderjson doesn't work in installed app
In the installed version of the client, the renderjson.js library fails with this error:

Uncaught ReferenceError: renderjson is not defined at renderjson.js:58

That line is:
(_module || {}).exports = renderjson = function () {

When the client is run from the command line, it works normally.

### PR DESCRIPTION
**Pull request by rmisio**
…er app

closes #672

### CODE REVIEW

File: js/lib/renderjson.js [hunk 1]
```diff
@@ -51,7 +51,7 @@
 //     .array.syntax  ("[", "]")
 
 var module;
-(module||{}).exports = renderjson = (function() {
+(module||{}).exports = window.renderjson = (function() {
```
Comment (jjeffryes) [inline js/lib/renderjson.js]: Should we add a comment somewhere that this has been modified so we don't overwrite it by updating the library?

**Comment by jjeffryes** [comment]
I'm merging this, but we'll need to test it with an installed version when we do our next release.
