### PR TITLE
Fix race condition in moderation

### LINKED ISSUE #948: Escrow payment text showing in payment screen on direct order
pasted image at 2017_09_26 02_08 pm

This is a direct order, but notice the text below the QR code stating it is an escrow order and that user can open a dispute.

The vendor did have a moderator, but I was unable to use moderated payments since the order size was too small.

### PR DESCRIPTION
**Pull request by jjeffryes**
Fixes a bug where a race condition caused the first moderator to be invisibly selected when the order total was too low for a moderator.

Closes #948

### CODE REVIEW

File: js/views/modals/purchase/Complete.js [hunk 1]
```diff
@@ -79,6 +79,14 @@ export default class extends BaseVw {
     e.preventDefault();
   }
 
+  get orderID() {
```
Comment (jjeffryes) [inline js/views/modals/purchase/Complete.js]: This is just cleaning up the code to use a getter and setter.

File: js/views/modals/purchase/Moderators.js [hunk 2]
```diff
@@ -184,7 +184,7 @@ export default class extends baseVw {
       this.removeNotFetched(model.id);
       this.modCards.push(newModView);
       // if required, select the first  moderator
-      if (this.options.selectFirst && !this.firstSelected) {
+      if (this.options.selectFirst && !this.firstSelected && !this.noneSelected) {
```
Comment (jjeffryes) [inline js/views/modals/purchase/Moderators.js]: noneSelected is set if no moderators should be selected.

This should be set to false if the total of the order is too low for moderation, since deselecting all the moderators won't affect moderators that aren't loaded yet.

File: js/views/modals/purchase/Purchase.js [hunk 3]
```diff
@@ -250,18 +251,20 @@ export default class extends BaseModal {
   disableModerators() {
     this.getCachedEl('#purchaseModerated').prop('checked', false);
     this.order.moderated = false;
+    this.moderators.deselectOthers();
     this.order.set('moderator', '');
   }
 
-  toggleModeration(bool) {
+  moderationOn(bool) {
```
Comment (jjeffryes) [inline js/views/modals/purchase/Purchase.js]: This was renamed to make the it more clear what true or false for the passed in value will do.
