### PR TITLE
Fix Linux scaling

### LINKED ISSUE #79: Add Zoom Handling for Linux
On startup, use electron.screen.getPrimaryDisplay().scaleFactor to adjust the scaling for Linux.

Something like the below should work:

if (platform === "linux") {
  var scaleFactor = require('electron').screen.getPrimaryDisplay().scaleFactor || 1;
  $("body").css("zoom", 1 / scaleFactor);
}

### PR DESCRIPTION
**Pull request by hoffmabc**
Fixes #79

### CODE REVIEW

File: js/start.js [hunk 1]
```diff
@@ -74,6 +76,15 @@ app.loadingModal = new LoadingModal({
   removeOnRoute: false,
 }).render().open();
 
+// fix zoom issue on Linux hiDPI
+if (platform === 'linux') {
+  let scaleFactor = screen.getPrimaryDisplay().scaleFactor;
+  if (scaleFactor === 0) {
+    scaleFactor = 1;
+  }
+  $('body').css('zoom', 1 / scaleFactor);
```
Comment (rmisio) [inline js/start.js]: Could we please use getBody from the utils/selectors.js file? It will cache that element so we only need to go to the DOM once for it.

**Comment by hoffmabc** [comment]
Ok @rmisio how's this look?

File: js/start.js [hunk 2]
```diff
@@ -18,11 +18,13 @@ import Followers from './collections/Followers';
 import listingDeleteHandler from './startup/listingDelete';
 import { fetchExchangeRates } from './utils/currency';
 import './utils/exchangeRateSyncer';
-import './utils/listingData';
+import { getBody } from './utils/listingData';
```
Comment (rmisio) [inline js/start.js]: getBody() is in utils/selectors.js. Did this code work when you ran it, or are you cowboy dev'in? lol
