### PR TITLE
fix issue where listing inventory is not saved on first save

### LINKED ISSUE #1244: Inventory doesn't seem to work
I'm on Windows 10 with the latest release. 

Reproduce:

1. Create or Clone a listing.
2. Fill out the form as it is displayed.
3. Click the dropdown for 'Inventory Management' and select 'Track Inventory'
4. Press tab and enter a number. Press tab to leave the box or click out of it.
5. Click Save.

Quantity will reset to 0.

Moreover, when an item with quantity of 1 is sold, this listing still appears purchasable to visitors. It may prevent the purchase from going through, I'm not 100% sure.

### PR DESCRIPTION
**Pull request by rmisio**
closes #1244

### CODE REVIEW

File: js/views/modals/editListing/EditListing.js [hunk 1]
```diff
@@ -893,14 +893,13 @@ export default class extends BaseModal {
     const excludes = '.js-sectionShipping, .js-couponsSection, .js-variantsSection, ' +
       '.js-variantInventorySection';
 
-    return this._$formFields ||
```
Comment (rmisio) [inline js/views/modals/editListing/EditListing.js]: The issue was that the quantity field is being dynamically rendered in after making a changing in its adjacent drop down and the form fields selector is already cached before that. Just going to turn off the cache for now.

**Comment by jjeffryes** [comment]
@rmisio can you fix the lint error in InventoryManagement? It doesn't use the _ any more. 

Otherwise this looks good to go.
